### PR TITLE
Upgrade to Scala 2.12.12

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by SethTisue** [comment]
`git grep 2\\.12\\.` shows that other files need updating

**Comment by ijuma** [comment]
Thanks. Looks like `rg` doesn't search files starting with `.` by default.

**Comment by ijuma** [comment]
One job failed due to a download timeout. The rest passed.

**Comment by SethTisue** [comment]
green on rebuild

thank you!

**Pull request merged**
